In [1]:
import numpy as np

In [2]:
np.array([1])

array([1])

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [6]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [9]:
print(x.ndim)

2


In [11]:
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x.ndim)

2


In [14]:
np.array((1, 2, 3))

array([1, 2, 3])

In [17]:
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x[0])
print(x[1,1])

[1 2]
4


In [24]:
print(x[::2])
print(x.dtype)
y = np.array([x], dtype='S')
print(y)
print(x.astype('f'))

[[1 2]
 [5 6]]
int32
[[[b'1' b'2']
  [b'3' b'4']
  [b'5' b'6']]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [26]:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x.copy() #copy doesnir affect the original array
y[0,1] = 10
print(y)
print(y.base) #base checks wehther the array is copy or view 
z = y.view() #view affects rhe original array
print(z)
print(z.base) 

[[ 1 10]
 [ 3  4]
 [ 5  6]]
None
[[ 1 10]
 [ 3  4]
 [ 5  6]]
[[ 1 10]
 [ 3  4]
 [ 5  6]]


In [27]:
print(x.shape)

(3, 2)


In [28]:
x.reshape(2,3,-1) #for 3D array 3rd dimension will be calculated automatically by using -1(-1 can be used only once)

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
for i in np.nditer(x, flags=['buffered'], op_dtypes=['S']): #we can avoid using multiple for loops to iterate #buffer is required to provide extra space to convert the data type
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


In [31]:
for j in np.nditer(x[:,::2]):
    print(j)

1
3
5


In [32]:
for idx, k in np.ndenumerate(x):
    print(idx, k)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
(2, 0) 5
(2, 1) 6


In [40]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(np.concatenate((x,y)))
print(np.stack((x,y))) #forms stack along rows
print(np.hstack((x,y))) #join along rows
print(np.vstack((x,y))) #stack along columns
print(np.dstack((x,y))) #stack along heights
print(np.array_split(x,4)) #splits the array #axis = 1 for split along rows #similarly hsplit, hstack, vsplit, dsplit, dstack 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
[array([[1, 2]]), array([[3, 4]]), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32)]


In [41]:
x = np.array([1,2,3,4,5,4,4,6,4])
np.where(x==4) #return tuple of indiced with value as 4

(array([3, 5, 6, 8], dtype=int64),)

In [43]:
x = np.array([5,6,7])
np.searchsorted(x,4,side='right') #return index at which given number to be inserted without disturbing the sorted order #side describes from where the search is to be started

0

In [44]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)


[1 2 3]


In [45]:
x = np.array([[5, 2, 3], [9, 0, -2]])
print(np.sort(x))

[[ 2  3  5]
 [-2  0  9]]


In [48]:
arr = np.array([1, 3, 5, 7])
x = [True, True, False, True] 
print(arr[x]) #prints number mcorresponding to True #filter_array
filter_array = arr>4
print(arr[filter_array])

[1 3 7]
[5 7]


In [53]:
from numpy import random
print(random.randint(100))
print(random.rand())
print(random.rand(2,3))
print(random.choice([1,2,3,4,5],size=(2,2)))

25
0.48808580805494983
[[0.58760998 0.45105451 0.72555797]
 [0.43386037 0.9449481  0.22720543]]
[[2 3]
 [4 2]]


In [58]:
x = np.array([1,3,5,7])
y = np.array([2,4,6,8])
for i,j in zip(x,y):
    print(i+j)
print(np.add(x,y))

3
7
11
15
[ 3  7 11 15]
